[build]
target = "armv5te-unknown-linux-gnueabi"

[target.armv5te-unknown-linux-musleabi]
linker = "rust-lld"

[target.armv5te-unknown-linux-gnueabi]
linker = "/usr/bin/arm-linux-gnueabi-gcc"

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "vendor"

# Optimize binary size
[profile.release]
lto = true
strip = "debuginfo"